### PR TITLE
Update parameter description

### PR DESCRIPTION
**Pull request by htsuruo**
Ref.
- #7

### CODE REVIEW

**Comment by htsuruo** [comment]
Hi, @pr-Mais  @cabljac 

I have a question about description in `extension.yaml`.

I added `TIMESTAMP_FORMAT` string parameter at previous version, and then wrote a description about the default value.

In the extension.yaml file, it is correctly written as ***YYYY-MM-DDTHH:mm:ss_SSS***.
https://github.com/HTsuruo/firebase-extensions/blob/5e5a2f6a73f8f99e0f6257fd5d1b8afb5243f463/back-up-firestore-to-storage/extension.yaml#L84

However, in the console when installing the Extension, it displays converted to lowercase as ***yyyy-mm-ddthh:mm:ss_SSS***. 

SCR-20230617-tbny-2

Why? This is not the expected behavior. Especially, for a Timestamp format, this is critical. 
How can this be resolved?

Thanks.

**Comment by pr-Mais** [comment]
Hi @HTsuruo! are you sure you published an RC based on this branch? it should be fixed by just updating the description in `extension.yaml`, try publishing another RC to make sure:
```
firebase ext:dev:upload HTsuruo/firebase-extensions --repo=https://github.com/HTsuruo/firebase-extensions --root=back-up-firestore-to-storage --ref=feature/tsuruo/fix-parameter-example
```

**Comment by htsuruo** [comment]
@pr-Mais 

Thanks for your reply.

> are you sure you published an RC based on this branch?

Yes, I published an RC based on this branch.

Here is Install Link.
https://console.firebase.google.com/project/_/extensions/install?ref=htsuruo%2Fback-up-firestore-to-storage@0.0.5-rc.0

However, the description is unexpected label in  Firebase Install console.
Could you check it out?

**Comment by pr-Mais** [comment]
I get the same as in your screenshot, could you try uploading a new RC? + What's the command you used to deploy? did it specify a `--ref`?

Probably unrelated but I noticed the `sourceUrl` is wrong:
https://github.com/HTsuruo/firebase-extensions/blob/a96ec5bd827dc25b60312e1628175edf97dbef35/back-up-firestore-to-storage/extension.yaml#LL14C1-L14C107

**Comment by htsuruo** [comment]
@pr-Mais 

> I get the same as in your screenshot, could you try uploading a new RC? + What's the command you used to deploy? did it specify a --ref?

Yes, I deployed with below commnad.

```sh
firebase ext:dev:upload htsuruo/back-up-firestore-to-storage --repo=https://github.com/HTsuruo/firebase-extensions --root=back-up-firestore-to-storage --ref=feature/tsuruo/fix-parameter-example
```

And then, I deployed to new RC  with the commit ( https://github.com/HTsuruo/firebase-extensions/pull/9/commits/c53977c2463e621c206dea4a3f04a92f600ed36a ). Result is here.

SCR-20230619-upgn-2

As you can see from the fact that  `YYYY-MM-DD` is displayed correctly, it seems that the colon(`:`) is the problem.
- `YYYY-MM-DDTHH:mm:ss_SSS` → `yyyy-mm-ddthhh:mm:ss_SSS`
- `YYYY-MM-DD`  → `YYYY-MM-DD`
- `HH:mm:ss_SSS` → `hh:mm:ss_SSS`

I suspect that **all the letters positioned before colon(`:`) are forced to convert lowercase**. Is it possible that this is a problem on the Firebase Console side? Or is some kind of escaping needed?

---

> Probably unrelated but I noticed the sourceUrl is wrong:
https://github.com/HTsuruo/firebase-extensions/blob/a96ec5bd827dc25b60312e1628175edf97dbef35/back-up-firestore-to-storage/extension.yaml#LL14C1-L14C107

Thanks! Fixed https://github.com/HTsuruo/firebase-extensions/pull/9/commits/ce00f77ecd289e4ba66e0e9cafeeab9a80cb1597.

**Comment by pr-Mais** [comment]
It seems to be a YAML parsing issue, check this [SO thread](https://stackoverflow.com/questions/11301650/how-to-escape-indicator-characters-colon-and-hyphen-in-yaml)

**Comment by htsuruo** [comment]
@pr-Mais 

> It seems to be a YAML parsing issue, check this [SO thread](https://stackoverflow.com/questions/11301650/how-to-escape-indicator-characters-colon-and-hyphen-in-yaml)

Yes, you are right.  Sorry, asking about an issue unrelated to Firebase Extensions 🙏
Thanks.

**Comment by pr-Mais** [comment]
No worries! anytime, escaping did work?

**Comment by htsuruo** [comment]
@pr-Mais 

> escaping did work?

Yes! 
I tried to change `YYYY-MM-DDTHH:mm:ss_SSS` to `YYYY-MM-DDTHH\:mm:ss_SSS` with escaping backslash(`\`), it works expectedly. 
(It seems that the code block word didn't work with this escaping, so changed it to bold style instead, that works. )
https://github.com/HTsuruo/firebase-extensions/pull/9/commits/dadabf0a1778a91f08c70c85735f5892bbeceafd#diff-3a075885ed29f8110a35b43cadd835f7bc1d6a6efe588d65d01505fc371afd10R88

**Pull request merged**
